# Generated by Django 2.1.5 on 2019-02-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('share', models.BooleanField(default=False)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
