# Generated by Django 2.1.5 on 2019-02-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
