# Generated by Django 2.1.5 on 2019-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='pubDate',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
