# Generated by Django 2.1.5 on 2019-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_auto_20190207_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='image',
            field=models.ImageField(upload_to='media/file'),
        ),
    ]
