# Generated by Django 2.1.5 on 2019-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0003_auto_20190207_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='image',
        ),
        migrations.AddField(
            model_name='req',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='req',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
