# Generated by Django 2.1.5 on 2019-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0004_auto_20190208_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='address',
        ),
        migrations.AddField(
            model_name='req',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
