# Generated by Django 2.1.5 on 2019-02-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0005_auto_20190208_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='session',
            field=models.CharField(default='', max_length=200),
        ),
    ]
