# Generated by Django 2.1.5 on 2019-02-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0006_req_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='session',
        ),
    ]
