# Generated by Django 2.1.5 on 2019-02-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190206_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choice2',
        ),
    ]
