# Generated by Django 2.1.5 on 2019-02-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190206_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice2',
            new_name='Choice',
        ),
    ]
